name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  dispatch:
      inputs:
        event_type: deploy
        description: Deploy to GitHub Pages
        client_payload: '{"source_branch": "main"}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build project
        run: |
          # If you have a build script, run it here
          # For now, we'll just copy the index.html to the output folder
          mkdir -p public
          cp index.html public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public