name: Run Main Script

on:
  schedule:
    - cron: "*/5 * * * *" # Workflows can only run a minimum of every 5 minutes, however even so, usually run about every 5-15 mins even when at 5.
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests nbtlib nbt aiohttp
          sudo apt-get update && sudo apt-get install -y sqlite3 gzip

      - name: Run main script
        run: |
          python __main__.py

      - name: Create compressed SQL dumps (snapshots)
        run: |
          python scripts/prepare_db_snapshots.py
          ls -lh *.sql.gz || true

      - name: Update README stats line
        run: |
          python scripts/update_readme_stats.py || true

      - name: Commit and push database changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.sql.gz index.html scripts/prepare_db_snapshots.py scripts/update_readme_stats.py README.md .gitignore || true
          if git diff --cached --quiet; then
            echo "No database changes to commit."
          else
            git commit -m 'Update database snapshots (legacy + v2) with new auctions'
            git push https://PAT:${{ secrets.PAT }}@github.com/UltimateBoi/AhAveragesPy.git HEAD:main
          fi
